# Site settings
title: Furkan Köykıran
description: Software Engineer - Python & Automation
# Analytics and Verification
google_analytics: "G-YRZ96D2VGX" # Add your Google Analytics ID here

webmaster_verifications:
  google: "" # Add your Google Search Console verification code
  bing: ""

# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://furkankoykiran.com.tr" # the base hostname & protocol for your site

# User settings
username: Furkan Köykıran
user_description: Software Engineer specializing in Python, Automation, and Scalable Systems. Experienced in building robust backend architectures and intelligent bot solutions.
user_title: Software Engineer | Python & Automation
email: furkankoykiran@gmail.com
twitter_username: furkankoykiran
instagram_username: furkankoykiran
facebook_username: furkankoykiran
linkedin_username: furkankoykiran
github_username:  furkankoykiran
# medium_username: 
# medium_url: 
# gplus_username:  lorem_ipsum


exclude: ['package.json', 'src', 'node_modules', 'vendor']

